devices:
    common: []
    debug: []
    release: []
dockercomposefile:
    common: ''
    debug: ''
    release: ''
extraparms:
    common: {}
    debug: {}
    release: {}
id: 5c53a1f2-9e4a-404d-aa16-f321b7a05715
images:
    debug: sha256:a5d3b114d2ecd9629772b1ef4c435ec82cc77978e9626d6c998dfbcccb29cd2b
    release: ''
imagetags:
    debug: tdx-python-qml_arm64v8-debian-python3-qt-vivante_bullseye_debug_5c53a1f2-9e4a-404d-aa16-f321b7a05715
    release: tdx-python-qml_arm64v8-debian-python3-qt-vivante_bullseye_release_5c53a1f2-9e4a-404d-aa16-f321b7a05715
modificationdate: '2022-08-10T12:49:14.879552'
networks:
    common: []
    debug: []
    release: []
otapackagename: ''
otapackageversion: 1.0.0
platformid: arm64v8-debian-python3-qt-vivante_bullseye
ports:
    common: {}
    debug: {}
    release: {}
privatekey: '-----BEGIN RSA PRIVATE KEY-----

    MIIEowIBAAKCAQEApTySwUbtgDgmyBHqkSz9rO6uInjf8bZdHBdITN+1mdL0RjRZ

    fkcYWYi9Ft4GchafVKI4PdJL2pLJ3qKhFva48VpQ/fTc8mw95ounDPzPvbukEYpn

    oHf8N++1fxFaSkVVKKpcFI/TdIw6ejtySOesaN/z7cdazAcpPIsQ9UPxUWEkg0Ll

    cDoLJddjyYhJHwFvbIb8zXNWBU5zssAy4WZhMCqfuEwXWrkcfOPwaWN+36Rqs3Rl

    1O58/kpexiJULHYlw0rq0O9buFhRXCC+aJISZrk3S5KcQ5W21cDxkM+Xaacx7RJt

    5X/69dkrQ8q3HR2MZSW5zux3jPg2CzF555iTEQIDAQABAoIBABc5oWMQpiIHQnmN

    UyF0EnVJLdQN62RH1A82Z+TY7jygfdHpr8k5Ev9wDIFMqdlFZsB4S1wdKqjz8vNG

    e/VaA9AgzWY0vGLyu0H5enyFLb9RwujtlvfjhYxojA6VO3yvAXOa0SCEFXO59h+S

    KtPRLyxP4N3Defatlv/kiCNWmR0X8S6fLetOG523wHZdMXdtSqJCAJ3qZxOwpTQ3

    A9f9JN4cC4GE2fcxGBlxsf1S4eOSFrOJajdUMYcxsCzrcXMG9niJMTDPlMJveQj4

    Vk3WkdtBCY0Wuh1faR8ftnkyCzcTEm3cv66UxqT74TI5KZAwmoR/ptZfX+LPYMdI

    CwkaY3UCgYEAtvG0mzPAcgZiX1rXo46ttFn0hIgzPi8bdwC7VV4IS0fwKkta1vYW

    KwimUvRd+1WO/bSYefU/wA2GycyVtIFgua11nYBL6WgIjwh5YRAWsHLogQLyZ4QW

    av9zNPv4fhcwqNsvNtNlUFqNfQlhRm1zUR1r1l11nQBfrkmZzNX73qsCgYEA5zii

    M3PqvwGzj2uiIqbTazIWetRdCGkEQ61VtQyxErHj8ny6F344j52Gaj9QjW36f4Yf

    hlxlgP5+9MDBY2U5fXpOdYv6bz87dW0sh965edID6t6mzitUZFfSpyXgI1eRjXsu

    n9VB3SC20+tA6vTEU3byhFCB+N0ndfYFLoO1pTMCgYBRnHnpUqjjNR3lU+0mtZuf

    /RErnmbdsr4Z1GW9q3kfvDPTalJX2ugAwpcQIptaZ8ymOU5b+aA62M3scCvInn67

    1jnFzVoQAazvweQD/N1iUaCPDPV+YFpv2Q1X8Z/lAAthCIaDesKTmhHMWcbfWCw9

    X1agBolVRLlqUsMdscfuiQKBgQDG8GhGQs7PxqP6mw3mKIkw6uiCiCL/cHO10vYy

    DxhvUFUitoPaYMRDdLJIye8BsIVdoUWQcgD3aoBLD2mUnmxHdKr64hP4EXyT/Pna

    cRw+Hx81vpngO1GiABoDrEfbwKVACKNF69N+cX48eWXigfRFJ8tjYm1hdM5V5PXy

    Xmo0FwKBgAj/EQ+IJwos/t9mrKrSirrIjQDnFGtxTV5mB8aw8se/ICUNFGW53RB5

    jFsUAmy7FL6ASW/Sj9uE3K0hlLqcXRRElf3OoY+ob3ywLER7Hft8dlJfgMx6S+gJ

    nE9D6TDClxn5G06nt8fqHsSCSisVSqYpOmPqntUqYNLb44ByirgX

    -----END RSA PRIVATE KEY-----

    '
props:
    common:
        appargs: ''
        appname: tdx-python-qml
        arg: ''
        buildcommands: ''
        buildfiles: ''
        command: ''
        devpackages: ''
        env: ''
        expose: ''
        extrapackages: ''
        language: python
        main: main.py
        preinstallcommands: ''
        runtime: python3
        sdkpostinstallcommands: ''
        sdkpreinstallcommands: ''
        targetcommands: ''
        targetfiles: ''
    debug:
        arg: 'ARG SSHUSERNAME=#%application.username%#

            '
    release: {}
publickey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQClPJLBRu2AOCbIEeqRLP2s7q4ieN/xtl0cF0hM37WZ0vRGNFl+RxhZiL0W3gZyFp9Uojg90kvaksneoqEW9rjxWlD99NzybD3mi6cM/M+9u6QRimegd/w377V/EVpKRVUoqlwUj9N0jDp6O3JI56xo3/Ptx1rMByk8ixD1Q/FRYSSDQuVwOgsl12PJiEkfAW9shvzNc1YFTnOywDLhZmEwKp+4TBdauRx84/BpY37fpGqzdGXU7nz+Sl7GIlQsdiXDSurQ71u4WFFcIL5okhJmuTdLkpxDlbbVwPGQz5dppzHtEm3lf/r12StDyrcdHYxlJbnO7HeM+DYLMXnnmJMR
sdkimages:
    debug: ''
    release: ''
sdkimagetags:
    debug: ''
    release: ''
sdksshaddress:
    debug: null
    release: null
shutdownscript:
    common: ''
    debug: ''
    release: ''
startupscript:
    common: ''
    debug: ''
    release: ''
username: torizon
volumes:
    common: {}
    debug:
        /home/torizon/tdx-python-qml: /tdx-python-qml,rw
    release: {}
