label: Qt for Python using QML
detail: >-
  $(window) Creates an application that uses the Qt for Python runtime and
  supports a dynamic User Interface defined using QML
tags:
  - qt
testing:
  - title: Python 3 Qt
    createCmd: torizon.createPythonApp
    projName: PythonQMLApp
    platformDistroCodeName: bullseye
    baseContainer:
      arm32v7: debian-python3-qt_bullseye
      arm64v8: debian-python3-qt-vivante_bullseye
    mainSourceFile: main.py
    mainSourceFileBreakPoint: 28
    programOutput: Hello world
    hasSDKContainer: false
    stopOnEntry: false
extversion: 1.6.0
